# Generated by Django 4.2.3 on 2024-10-29 05:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="URL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_url", models.URLField(unique=True)),
                ("short_id", models.CharField(blank=True, max_length=8, unique=True)),
                (
                    "custom_slug",
                    models.CharField(blank=True, max_length=30, null=True, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("access_count", models.IntegerField(default=0)),
            ],
        ),
    ]
