# Generated by Django 4.2.3 on 2024-10-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shortener", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="short_id",
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
